### ISSUE TITLE
Set-PromptColor should effect Add-PromptColor when the named color doesn't exist

### ISSUE THREAD

**Issue by DHowett** [jimmehc/PromptEd#1]
`Set-PromptColor` should act as `Add-PromptColor` when the color doesn't exist. Right now, there's a distinction between adding and setting prompt colors.
I propose the distinction be removed. Right now, modules that have overlapping functionality and consume PromptEd will throw errors on load if they attempt to add the same prompt color. The same applies to custom profiles and user prompts.

As an example, my profile contains:

```ps1
	Add-PromptColor Provider DarkMagenta
	Add-PromptColor Sigil Green
	Add-PromptColor Hostname White
	Add-PromptColor DevEnv Green

	Add-PromptColor CommandTime Black
	Add-PromptColor CommandTimeBrackets Black

	# These are already defined by PromptEd
	Set-PromptColor Path Magenta
	Set-PromptColor Brackets Blue
```

Unfortunately, I can't be _totally certain_ that a PromptEd update won't reserve some of the names I've used.

**Comment by jimmehc** [comment]
That sounds pretty reasonable.  I can't remember what my thought process was when writing those, but I don't believe I had any strong reasons for strictly separating adding and setting into different functions.  Will fix.

**Comment by DHowett** [comment]
Outstanding. Thanks!
